### ISSUE TITLE
Public exposure of classes / properties and some explanations if possible

### ISSUE THREAD

**Issue by CorsairRO** [ElinamLLC/SharpVectors#94] opened 2019-03-13 07:11 UTC
Hello and thank you for sharing such a nice library with us...

I need a library like this to use in my WPF applications.

However I have some questions ...

0) My goal is to Load / Store some SVG files in the database, and give the user the possibility to change them. I do not care at all about xaml and other stuff.

I need just to be able to:
- Show a SVG Image ( I can do this by using one of your controls )
- Allow User to Add some shapes to the screen and move them around by mouse
- Save his changes back to database.
- I don't care anything about any xaml conversion or something else like this.

My app is WPF.

1) SVGCanvas and SVGDrawingCanvas

What is the difference?
None of them works like a real canvas, because I tried to add some lines to the Children property and it didn't show up, while in the normal WPF Canvas it works.
If I understood wrong what a canvas should be, please let me know, or if you have some other suggestions will be very appreciated.

2) Like somebody else pointed out earlier in the thread, please make all the properties public so that we do not need reflection to access them.

Also, some properties are not accessbile at all, as they are created on the fly and never stored anywhere.
Examples are: SVGImage, and all the manipulation of drawings / groups and so on.

For this, I tried the reflection to get the drawings rendered, and trying to add something to that collection.
Now, question is: What do I do to show them onto the screen.

3) In the same area, I found a Winforms old Library for SVG that holds a reference to the SVG Dom, and expose it publicly, while the rendered stuff is a GDI Image. Working over the image updates accordingly the SVg DOM.
THis sounded like an interesting idea to follow, but in your library here I cannot find any place to access the Loaded SVG DOM. 

Do I need to save/load in a FILE every time that it is manipulated?

Thank you for your answrers,
Have a nice day.

_Originally posted by @CorsairRO in https://github.com/ElinamLLC/SharpVectors/issues/88#issuecomment-470044525_

**Comment by paulushub** [comment] 2019-03-17 04:19
> 0. My goal is to Load / Store some SVG files in the database, and give the user the possibility to change them. I do not care at all about xaml and other stuff.

Your goal is understood, but it seems this might not be the library for it.

- Show a SVG Image ( I can do this by using one of your controls )
    Yes, it is SVG to WPF format converter library with controls provided to **view** the outputs.
- Allow User to Add some shapes to the screen and move them around by mouse: 
    No, no control provided for editing. Even if one is provided, the output will be in XAML.
- Save his changes back to database.
    No, as said earlier, the result of the conversion is WPF/XAML format.
- I don't care anything about any xaml conversion or something else like this.
    Basically, you have SVG to WPF conversion library - not really much!

> 1. SvgCanvas and SvgDrawingCanvas

- SvgDrawingCanvas:
    - It derives from the the WPF Canvas and hence the name. 
    - Is the basic unit for **viewing** the SVG to WPF output.
    - Is is available in SharpVectors.Runtime.Wpf.dll, which you can ship with your application to view the converted XAML files if you do not want to ship the full library.
    - SharpVectors.Runtime.Wpf.dll does not depend on other library components, so SvgDrawingCanvas does not handle conversion by itself.
- SvgCanvas
    - It derives from SvgDrawingCanvas and hence the name canvas.
    - It is part of the SharpVectors.Converters.Wpf.dll and directly converts the SVG for viewing.

By the WPF Canvas definition: 
> Defines an area within which you can explicitly position child elements by using coordinates that are relative to the Canvas area.

The "child elements" are WPF Visual elements. Now, the SvgDrawingCanvas, which is optimized for viewing uses a single DrawingVisual element to render the DrawingGroup output and position that on the canvas.
The current output from the conversions are Drawing elements, which are low-level WPF elements that do not provide mouse/keyboard interactivity since they are not Visuals. WPF provides several drawing options, the Drawing elements are used by this library for performance reasons.
I have planned to add other drawing options like DrawingVisual and Shape and also support UWP but do not currently have the resources for all that yet.

> 2. Like somebody else pointed out earlier in the thread, please make all the properties public so that we do not need reflection to access them.

This is already completed and committed to the repository.
- SvgDrawingCanvas: In fact, there is no need to "expose" the drawings in this case, since any drawing used by this canvas is externally done by you and you already have the access, unless you do not save it.
- SvgCanvas and SvgViewbox drawings are exposed through properties.
- SvgImage and SvgImageConverter are MarkupExtension derived classes. You do not have direct access to the actual classes (SvgImageExtension and SvgImageConverterExtension), and the output (DrawingImage) is based on request by the WPF framework, it is not stored.
- If you need customization to the SvgImage or SvgImageConverter, derive from their common base class SvgImageBase, which does the actual conversions and customize it to your needs. 

> 3. In the same area, I found a Winforms old Library for SVG that holds a reference to the SVG Dom, and expose it publicly, 

That is part of the planned features: #22. The planned improvements to the SvgCanvas and SvgViewbox control, which handle conversion, is to eliminate the use of the converters and directly control the conversions.
Currently, only the converters have access to the SVG DOM. The original target of the library was conversion. Controls and markup extension classes were added later by requests.

That said, this is basically a library in different parts. The converter classes (deriving from SvgConverter) are simply convenient classes. You really do not need any of such classes, since these are only using the classes in SharpVectors.Rendering.Wpf to simplify the conversion process.
This is by design to give developers access to all aspect of the library features, and is one main advantage the SharpVectors provides over the alternatives! 

If you only need the SVG DOM, SharpVectors,Model.dll and its referenced libraries are all you will need etc.

**Closed** 2019-04-01 18:45 UTC
