### ISSUE TITLE
Wrong rect displaying

### ISSUE THREAD

**Issue by Kozinaka** [ElinamLLC/SharpVectors#95] opened 2019-03-13 08:31 UTC
There are sample of two similar files with single rect 32x32 px size. Both of them editable by Inkscape and don't change it's behaviour after resaving in it. Right.svg displaying right, Wrong.svg displaying with error (rendered rect is smaller than expected).

Files to test: [Samples.zip](https://github.com/ElinamLLC/SharpVectors/files/2960440/Samples.zip)

![RightPreview](https://user-images.githubusercontent.com/10096369/54264015-342e6980-4583-11e9-86c0-0e767fceb57a.png)

![WrongPreview](https://user-images.githubusercontent.com/10096369/54264020-38f31d80-4583-11e9-88ce-64a805e5f601.png)

**Comment by paulushub** [comment] 2019-03-17 02:04
@Kozinaka I have found the source of the issue, but there is no fix needed.

In both conversion (see the Xaml Output), a root clipping region is added due to the defined size of 32 by 32.
```xml
    <DrawingGroup.ClipGeometry>
      <RectangleGeometry Rect="0,0,32,32" />
    </DrawingGroup.ClipGeometry>
```
The clipping region in the output is affecting the "wrong" output file. There is no need for a fix because the conversion settings allow you to turn on or off the root clipping region through a property named **IgnoreRootViewbox**, which is `false` by default and is used as such in the **WpfSvgTestBox** application.
Setting this property to `true` in the **SvgPage.xaml.cs** constructor will give the same output for both files.
`_wpfSettings.IgnoreRootViewbox = true;`

I will update the WpfSvgTestBox application to make the conversion settings available to turn on or off the options and observe the effects on the outputs.

**Comment by Kozinaka** [comment] 2019-03-17 07:14
But both files contains one single green rect [0,0,32,32] inside of it in Inkscape and both of it have clip region [0, 0, 32, 32]! Why "wrong" file have something outside [0,0,32,32] when output in SharpVectors?

**Comment by paulushub** [comment] 2019-03-17 08:22
Nice observation, thank you. It is a bug in the current `SvgNumber.ScientificToDec` method.

**Comment by paulushub** [comment] 2019-03-17 08:45
Thanks for submitting this issue, I think it have now fixed it in the committed code 5bc43247644b602474793c21cdc3698a1a05e285.
Please verify the fix.

**Comment by Kozinaka** [comment] 2019-03-19 09:16
Build is broken :)
..\Source\SharpVectorModel\BasicTypes\SvgTransform.cs:
'SvgNumber.DoubleRegex' is inaccessible due to its protection level

**Comment by paulushub** [comment] 2019-03-19 12:25
Sorry, but my local repository is not broken!!! 
I will have to commit all changes (many are unfinished work!) to fix this issue, let me review my local sources first, sorry for the inconvenience.

**Comment by paulushub** [comment] 2019-03-19 13:15
The review will take time, I think committing the SvgTransform class will fix the problem build.

**Comment by paulushub** [comment] 2019-03-27 06:46
Finally committed  all the local changes: ad7b893660c31eba18dba84e36145dab4d216e97

**Comment by Kozinaka** [comment] 2019-04-03 11:54
But now it explodes in runtime when loading some icons. :)
F.e. **WpfSvgTestBox** crashes when try to load this icon: [Front32.zip](https://github.com/ElinamLLC/SharpVectors/files/3038462/Front32.zip)

**Comment by paulushub** [comment] 2019-04-03 13:18
@Kozinaka Sorry, I could not reproduce this latest issue. The attached icon is rendered normally as shown below:

![Front32](https://user-images.githubusercontent.com/809351/55481868-3f465800-565e-11e9-87a3-319ff0c69426.png)

**Comment by Kozinaka** [comment] 2019-04-04 06:57
You did forget to add your independent number format to decimal.Parse. In Russian format dot is decimal delimiter, not comma.

![Fix](https://user-images.githubusercontent.com/10096369/55535445-ee674b80-56bf-11e9-91e8-8c88828a61d2.png)

**Comment by paulushub** [comment] 2019-04-05 14:46
@Kozinaka Not having access to Russian Windows (only English and Japanese) but was able to reproduce the parsing error with `var culture = CultureInfo.GetCultureInfo("ru-RU");`.
Hope the latest commit will now fix the issue.

**Closed** 2019-04-28 05:57 UTC
