### ISSUE TITLE
Huge performance downgrade in 1.4 version WPF SVG to DwawingGroup conversion

### ISSUE THREAD

**Issue by Mikolaytis** [ElinamLLC/SharpVectors#119] opened 2019-11-27 23:31 UTC
If you will create a simple benchmark with different svg files conversion from svg to DwawingGroup you will notice 10-20 time worse performance in 1.4 version compared to 1.3.
Is there any way (in settings maybe) to get old nice performance?

**Comment by paulushub** [comment] 2019-11-28 11:13
@Mikolaytis Thanks for the information. I have not noticed that effect, will look into it.
The current version is 1.5, are you still experiencing the downgrade?

**Comment by Mikolaytis** [comment] 2019-11-28 14:22
Yes, I've tried and tested all the versions. 1.2 have the best performance. So i'm using it for now in my apps.

**Comment by paulushub** [comment] 2019-11-28 20:01
Thanks for the feedback.

**Comment by widi8835** [comment] 2019-12-10 20:22
I observed the same performance drop since v1.4. I guess the problem is caused by the 'GC.Collect()' statement in SvgConverter.cs (are there other usages?). I don't know much about the garbage collector, but you should not call 'GC.Collect()' explicitly. If it's appropriate you can call GC.SuppressFinalizer and otherwise let the GC do its magic.
I hope that helps.

**Comment by paulushub** [comment] 2019-12-11 13:02
@widi8835 The call to GC.Collect() is marked as **//TODO: Currently, experimental**. I do not know it is having huge effect on performance - I will look into it.

**Comment by Kozinaka** [comment] 2020-01-21 11:31
I faced the same performance drop in version 1.4.0.0.

I've attached solution with example of this effect (there are two test frojects inside for 1.3 and 1.4 versions of SharpVectors). 
[SharpVectorsTest.zip](https://github.com/ElinamLLC/SharpVectors/files/4090820/SharpVectorsTest.zip)

In my synthetic test, the performance drop is 4 times. In a real project, the drop is 10 times, because we use a debug build.

![3vs4test](https://user-images.githubusercontent.com/10096369/72801396-796aff80-3c5a-11ea-8094-984a87917c0a.png)

In version 1.4, loading the same icon several times each subsequent download becomes slower than the previous one.

**Comment by Kozinaka** [comment] 2020-01-21 12:03
**P.S.** Removing GC.Collect(); from SvgConverter.cs fixes the problem. At least at first glance, I did not find any additional problems.

**Comment by paulushub** [comment] 2020-01-22 13:45
@Kozinaka Welcome back! Thanks for the tests. I got similar results on my current PC running Windows 10 (CPU: Xeon E3-1226 @3.3GHz, GPU: Quadro K2200).
The performance of the current repository sources is similar to the v1.3.

**Comment by Kozinaka** [comment] 2020-01-23 06:38
Hey! :) 

I cant use last sources of SharpVectors on my Visual Studio 2017 (looks like it needs VS2019), but v.1.5 from NuGet demonstrates the same problem with GC. 
![1_5_FromNuGet](https://user-images.githubusercontent.com/10096369/72961908-cae2ce00-3dc3-11ea-92a1-cdeaf70b8084.png)

**Comment by paulushub** [comment] 2020-01-23 11:38
> I cant use last sources of SharpVectors on my Visual Studio 2017 (looks like it needs VS2019),

True, the support for Core 3.x requires VS2019, but I am looking into it. 
We could add VS2017 version of SDK-style projects (since these do not require adding files to the project, which could make maintenance difficult). These could target frameworks other than Core 3.x.

**Comment by paulushub** [comment] 2020-03-24 20:13
@Kozinaka I have now added VS2017 solutions and projects. These use the SDK-style formats and support multiple versions of the .NET framework; .NET4.0, .NET4.5, .NET4.6, .NET4.7 and .NET4.8.

**Comment by Kozinaka** [comment] 2020-03-25 12:06
@paulushub It works! :) I have assembled last version of the lib with VS2017, and test if for subject bug — perfomance downgrade is not reproduced. Thank you!

**Comment by paulushub** [comment] 2020-05-17 19:42
@Mikolaytis I have just released version 1.6 with some rendering optimizations and removal of the `GC.Collect()` calls. Please put this to the test!

**Closed** 2020-11-18 22:09 UTC
Labels: enhancement, task
