### ISSUE TITLE
Stuck in parsing css in some svg.

### ISSUE THREAD

**Issue by kkwpsv** [ElinamLLC/SharpVectors#206] opened 2021-08-24 10:13 UTC
The stack when stuck is as below:

![image](https://user-images.githubusercontent.com/11524048/130598152-ff4cce8e-d6ad-4b2e-9fe3-a3d6fc2f17c9.png)

Here is two svgs which caused stuck. 
[svg.zip](https://github.com/ElinamLLC/SharpVectors/files/7038376/svg.zip)

**Comment by kkwpsv** [comment] 2021-09-09 10:28
It may be realted to regular expression backtracking.

**Comment by marksolbergerbjorkerot** [comment] 2021-09-20 12:23
Reproduced fail during css-parsing with the following data:
[failed-svg-regexp.zip](https://github.com/ElinamLLC/SharpVectors/files/7195637/failed-svg-regexp.zip). RegEx.Match hangs becomes caught in a loop.

**Comment by paulushub** [comment] 2021-09-20 12:52
@marksolbergerbjorkerot Thanks for tracking this issue. There is another problem with this issue; the original SVG test file contains embedded WOFF2 format font, which is not fully supported by the SharpVectors. I am currently trying to complete that support and then take on the CSS parsing.

**Comment by marksolbergerbjorkerot** [comment] 2021-09-20 13:11
@paulushub - it seems that CssRuleList never breaks the while-loop when no at-rules have been able to be parsed. It just keeps looping the same css over and over. Changing the UnknownCssRule regex-pattern no ^@[^;]+;? (making the last semi-colon optional) will render a match on the rule for cases where no semicolon exists and the while-loop will break.

**Comment by paulushub** [comment] 2021-09-26 22:09
@marksolbergerbjorkerot I have completed the WOFF1/WOFF2 decoder codes and started testing this issue.
It seems the only fix required here is `_reSplitCss` in the `CssStyleDeclaration`. 
Changing this to the fix in your fork/commit (**change _reSplitCss by removing match any**) seems to resolve both issues reported above.
```csharp
private static readonly Regex _reSplitCss = new Regex(@"([^:\s]+)*\s*:\s*([^;]+);");

// changed to

private static readonly Regex _reSplitCss = new Regex(@"([^:\s]+)\s*:\s*([^;]+);");
```

**Comment by paulushub** [comment] 2021-09-27 03:39
@kkwpsv @alo00 @marksolbergerbjorkerot It seems this issue is resolved by the latest commit. Please can you verify this fix.

@kkwpsv The embedded WOFF2 fonts are never used. Are you using these fonts? The fonts were decoded and successfully tested, but no verification is done in your test file, since there is no text to be rendered.

**Comment by kkwpsv** [comment] 2021-09-30 01:46
I have test the latest version with my sample file, it works fine.
The svg file is not from myself, i don't know why it embed font and not use.
I have modified it to use font embeded. It seems also works fine.

[svg with woff2 sample.zip](https://github.com/ElinamLLC/SharpVectors/files/7255969/svg.with.woff2.sample.zip)

**Comment by paulushub** [comment] 2021-09-30 02:03
@kkwpsv Thanks for the updates.

**Comment by Whiletru3** [comment] 2021-12-07 11:52
Is there any plan for a new release including this fix ?

Thanks

**Comment by paulushub** [comment] 2021-12-07 11:55
@Whiletru3 Will trying to get it out by Monday. Currently, busy looking for a new job 😢

**Comment by Whiletru3** [comment] 2021-12-07 13:04
@paulushub Thanks a lot :) Good luck for your search 👍

**Closed** 2021-12-12 18:01 UTC
Labels: bug, Impact: High
