### ISSUE TITLE
Multiple render exceptions  ver 1.7.1

### ISSUE THREAD

**Issue by amoraller** [ElinamLLC/SharpVectors#173] opened 2021-03-03 14:30 UTC
I have a WPF application for production with more svg files. 
After update package from 1.6.0 to 1.7.1 some users have multiple errors for my app. 

I can not get minimal crashed example, because i can not repeat this problem. I have only logs from my app. 
Problems has only windows 10 users after 5-10 minutes on running. While exceptions throwning all another apps( incl. mouse cursor) freezing

Some Exceptions 
**System.Runtime.InteropServices.COMException MILERR_WIN32ERROR (Исключение из HRESULT: 0x88980003)**
```
 в System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()
   в System.Windows.Media.Imaging.RenderTargetBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat)
   в MS.Internal.AppModel.IconHelper.GenerateBitmapSource(ImageSource img, Size renderSize)
   в MS.Internal.AppModel.IconHelper.CreateIconHandleFromImageSource(ImageSource image, Size size)
   в MS.Internal.AppModel.IconHelper.GetIconHandlesFromImageSource(ImageSource image, IconHandle& largeIconHandle, IconHandle& smallIconHandle)
   в System.Windows.Window.UpdateIcon()
   в System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   в System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   в System.Windows.Window.CreateSourceWindowDuringShow()
   в System.Windows.Window.SafeCreateWindowDuringShow()
   в System.Windows.Window.ShowHelper(Object booleanBox)
   в System.Windows.Window.Show()
   в System.Windows.Window.ShowDialog()
   в TecProgV2.WpfCore.MVVMTools.WinWrapper.<>c__DisplayClass4_0.<.ctor>b__6()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**System.Runtime.InteropServices.COMException UCEERR_RENDERTHREADFAILURE (Исключение из HRESULT: 0x88980406)**
```
 в System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   в System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   в System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**System.ComponentModel.Win32Exception the operation completed successfully**
```
в Standard.NativeMethods.CreateRoundRectRgn(Int32 nLeftRect, Int32 nTopRect, Int32 nRightRect, Int32 nBottomRect, Int32 nWidthEllipse, Int32 nHeightEllipse)
   в Microsoft.Windows.Shell.WindowChromeWorker._CreateRoundRectRgn(Rect region, Double radius)
   в Microsoft.Windows.Shell.WindowChromeWorker._SetRoundingRegion(Nullable`1 wp)
   в Microsoft.Windows.Shell.WindowChromeWorker._UpdateFrameState(Boolean force)
   в Microsoft.Windows.Shell.WindowChromeWorker._ApplyNewCustomChrome()
   в Microsoft.Windows.Shell.WindowChromeWorker.<_SetWindow>b__1(Object sender, EventArgs e)
   в System.Windows.Window.OnSourceInitialized(EventArgs e)
   в TecProgV2.WpfCore.Wpf4Window.OnSourceInitialized(EventArgs e)
   в System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   в System.Windows.Window.CreateSourceWindowDuringShow()
   в System.Windows.Window.SafeCreateWindowDuringShow()
   в System.Windows.Window.ShowHelper(Object booleanBox)
   в System.Windows.Window.Show()
   в System.Windows.Window.ShowDialog()
   в TecProgV2.WpfCore.MVVMTools.WinWrapper.<>c__DisplayClass4_0.<.ctor>b__6()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**System.OutOfMemoryException**
```
 в System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   в System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   в System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

https://docs.microsoft.com/ru-ru/troubleshoot/dotnet/framework/wpf-render-thread-failures

Windows 10
Net Framework 4.0
SharpVectors 1.7.1

**Comment by paulushub** [comment] 2021-03-03 18:57
@amoraller Sorry for this. None of the tracings includes SharpVectors, was this the only library you updated?
`TecProgV2.WpfCore` seems to be featuring on the stalk.
Also, looking at the MSDN documentation link, none of the operations is to be related to SharpVectors rendering process.

**Comment by amoraller** [comment] 2021-03-04 05:59
@paulushub yes. I update only SharpVectors library. After downgrade library version my users have not problem. 

Article on link 
```
These are symptoms of a failure in the render thread. This is a challenging problem to diagnose because the exceptions and call stacks received are generic. Render thread failures will generate one of the calls stacks shown above (or a minor variation thereof) regardless of the root cause. This makes diagnosing the problem, or even recognizing when two crashes or hangs stem from the same root cause, especially difficult.
```

I can not regular reproduct or reproduct on my PC. Mabye has another library users with this problem?

**Comment by paulushub** [comment] 2021-03-08 10:50
@amoraller Thanks for the updates, I will look into it. A little difficult since it is not easily reproducible. 
Any way you can get the environment configuration of the PC where these occur?

**Comment by paulushub** [comment] 2021-03-10 14:53
It looks like a x64 system, even though I could not read the Russian. x86 app on x64 system ,Could that be a hint?

**Comment by amoraller** [comment] 2021-03-11 06:42
@paulushub  i think, ```DpiUtilites.GetSystemEffectiveDpi``` has DC leaks, because you invoke ```NativeMethods.GetDC``` and not invoke ```NativeMethods.ReleaseDC```. 
Please see this method:
```cs
        public static void GetSystemEffectiveDpi(out uint dpiX, out uint dpiY)
        {
            using (Graphics g = Graphics.FromHwnd(IntPtr.Zero))
            {

                IntPtr handle = g.GetHdc();
                int x = NativeMethods.GetDeviceCaps(handle, (int) NativeMethods.DeviceCap.LOGPIXELSX);
                int y = NativeMethods.GetDeviceCaps(handle, (int) NativeMethods.DeviceCap.LOGPIXELSY);

                // If anything goes wrong, return a reasonable DPI

                dpiX = x > 0 ? (uint) x : _defaultPixelsPerInch;
                dpiY = y > 0 ? (uint) y : _defaultPixelsPerInch;
                g.ReleaseHdc(handle);
            }

        }
```

Sorry, i don`t understand, why you recalc effective DPI regular. Mabye you can recalulate effective DPI only if screen configuration changed?

**Comment by paulushub** [comment] 2021-03-11 11:55
Thanks for the updates. `DpiUtilites` is released as part of a project by a MS team, it seems I trusted it too much. It was the source of the bug that made it necessary to issue an immediate fix for 1.7 in 1.7.1.

`SharpVectors` is a library, and it only tries to retrieve the DPI if not provided by the user who should have access to the application window. The DPI is stored in the document, so anytime a new document is initialized it will try to retrieve the DPI.

**Comment by amoraller** [comment] 2021-06-01 16:48
@paulushub thanks. Fix worked for me

**Comment by paulushub** [comment] 2021-06-01 18:33
@amoraller Thanks. Any update on the main issue? **Multiple render exceptions**

**Comment by amoraller** [comment] 2021-06-01 19:28
@paulushub No. Commit ea0bd9eedfec003814fdc16f9d2b33efb0bd2e21 fix my problem. Please create new verison with fix on NuGet.

**Comment by AppyxDaniel** [comment] 2021-08-30 10:04
I think I still can reproduce the same issue.
Tested with 1.7.1. 1.7.5 and 1.7.6 in WPF.
Runtime: .NET Core 3.1.17
Windows 10 x64

Exception: 
```
------------------- Exception Stacktrace: ------------------
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
-------------------- Exception Details: --------------------
ErrorCode = -2003303418
TargetSite = Void SyncFlush()
StackTrace =    at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
Message = UCEERR_RENDERTHREADFAILURE (0x88980406)
Data = System.Collections.ListDictionaryInternal
InnerException = 
HelpLink = 
Source = PresentationCore
HResult = -2003303418
-------------------------------------------------------------
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Background Information: 

We have a list view where each item has a SVG Icon. The icon source is bound to a property which is just the path to the SVG resource.
The list view is part of a data template. When the data context changes, the SVG icon paths are reevaluated.

In this case it seems that the creation of the list view items container fails, since only the first few items (sometimes even no items at all) are visible and the other items stay empty. When the user then scrolls in the list view, the application completely freezes, the exception above occurs at some point and the application finally crashes.

If the SVG image is removed from the list view item template, or if the source is set to fixed value everything works as expected.
As a workaround we hold all possible icons in the list view item data template and only show the correct one.

It seems like fast source changes could lead to this issue.

**Comment by paulushub** [comment] 2021-08-30 10:26
> It seems like fast source changes could lead to this issue.

Thanks for the hint and the description of your test case.

**Comment by panagiotis-bitharis** [comment] 2021-11-04 06:46
I can still reproduce the error on 1.7.6 on a WPF application .NET Framework 4.8
The error takes a few minutes before it starts appearing and the error is thrown after the following block of code is executed. Perhaps some kind of memory leak?

`using (var svgreader= new FileSvgReader(DefaultWpfDrawingSettings))
using (var stringreader = new StringReader(svgData))
{
	var drawing = svgreader.Read(stringreader);
	var iconXaml = XamlWriter.Save(drawing);
}`

Exception:

`System.ComponentModel.Win32Exception (0x80004005): Not enough memory resources are available to process this command
   at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32 dwExStyle, String lpszClassName, String lpszWindowName, Int32 style, Int32 x, Int32 y, Int32 width, Int32 height, HandleRef hWndParent, HandleRef hMenu, HandleRef hInst, Object pvParam)
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Threading.Dispatcher..ctor()
   at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
   at SharpVectors.Converters.SvgConverter..ctor(WpfDrawingSettings settings)
   at SharpVectors.Converters.FileSvgReader..ctor(Boolean saveXaml, Boolean saveZaml, DirectoryInfo workingDir, WpfDrawingSettings settings, Boolean isEmbedded)
   at Server.Services.WebPages.Private.SvgIconConverter.TryConvertToXaml(WebPageIcon svgIcon, String& xamlIcon)`

**Comment by paulushub** [comment] 2021-11-04 07:40
@panagiotis-bitharis What is your test environment?

**Comment by panagiotis-bitharis** [comment] 2021-11-04 09:13
> 
> 
> @panagiotis-bitharis What is your test environment?

Windows 10 Enterprise x64

**Comment by paulushub** [comment] 2021-11-04 11:23
@panagiotis-bitharis The line `Server.Services.WebPages.Private.SvgIconConverter` seems to indicate a web page application.

**Comment by paulushub** [comment] 2022-06-10 20:49
Hopefully, this issue is resolved. If not reopen it.

**Closed by paulushub** 2022-06-10 20:49 UTC
